### PR TITLE
Fix #10: rustfmt now uses the correct rustfmt.toml

### LINKED ISSUE #10: Using rustfmt.toml when formatting
I want to use the format-on-save feature with some custom rustfmt options. Sadly it seems that AnacondaRust does not spawn `rustfmt` correctly. Rustfmt automatically checks in the current directory and parent directories for a `rustfmt.toml` file and uses it as configuration. But when using AnacondaRust it does not use my custom configuration. I think the easiest solution is to spawn `rustfmt` with the files directory as working directory. 

It might also be interesting for some to specify the `--config-path` of rustfmt in the AnacondaRust configuration.

I'd really appreciate if someone could look into this :)

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
This is my attempt to fix #10 ... as I already mentioned in the issue I don't know anything about python and sublime plugin development. This solution works for me, but someone should do some proper code review ^_^

### CODE REVIEW

**Comment by DamnWidget** [comment]
It looks fine, I am gonna tune it a bit to add a configuration option to override it and use `--config-path` in case that the user defines any.

**Comment by LukasKalbertodt** [comment]
Thanks for the quick update and improvement of the code!

However, I think there is a small bug: you use the project's folder path as if it's always absolute. This doesn't need to be the case. My projects often specify the path relative to the `sublime-project` file. So for example, it might look like `"path": "."`. 

A possible solution would be to prefix `os.path.dirname(sublime.active_window().project_file_name())` in case the `path` is not absolute. 

Shall I open a new issue or will you fix that soon anyway? :)

**Comment by DamnWidget** [comment]
I don't understand what you mean, I am taking the project directory path as it is always specified by the ST3 project data information that it will always be an absolute path.

Can you elaborate what you mean about your projects please?

Regards.

**Comment by LukasKalbertodt** [comment]
No, it's not always absolute. I added `print("path: " + config_path)` after [this line](https://github.com/DamnWidget/anaconda_rust/blob/0a89d3e92b3558387def06f1c0f43a422839b097/commands/rustfmt.py#L60) to see what the config_path is. I use this project configuration:

``` json
{
    "folders":
    [
        {
            "folder_exclude_patterns":
            [
                "target"
            ],
            "path": "."
        }
    ]
}
```

And whenever I save a file and the rustfmt-function is called, it prints `path: .` on the console.

**Comment by DamnWidget** [comment]
Can you run the following directly in the ST3 console and paste here the output please?

``` python
print(window.project_data())
```

**Comment by LukasKalbertodt** [comment]
In the config above I removed some things I considered not important, but here you go, the raw output:

```
{'folders': [{'file_exclude_patterns': ['*.lock', 'LICENSE-*', '*.rs.bk', '*.sublime-*'], 'folder_exclude_patterns': ['target', 'ci'], 'path': '.'}], 'settings': {'rulers': [80, 100], 'tab_size': 4, 'use_tab_stops': True, 'translate_tabs_to_spaces': True}, 'build_systems': [{'selector': 'source.python', 'shell_cmd': '"python" -u "$file"', 'name': 'Anaconda Python Builder', 'file_regex': '^[ ]*File "(...*?)", line ([0-9]*)'}]}
```

**Comment by DamnWidget** [comment]
I see what you mean, the problem with the `project_file_name` approach is that not always there is a project file, ergo there is no file name. I think we can try to use `project_file_name` and if it's `None` we can fallback to `window.folders()` and then fallback one more level into `view.file_name()`.

What do you think?

**Comment by LukasKalbertodt** [comment]
But I guess `project_file_name` exists exactly if and only if `active_window().project_data()` exists, right? And we only need it in that case?

The project and `window.folders()` solution also has the problem that we would have to search through multiple folders. Just taking the first one, as you are currently doing, is not really a superb solution IMO.

I think in nearly all cases the `view.file_name()` path is what people want `rustfmt` to run in. Maybe we should just ignore the other cases?

**Comment by DamnWidget** [comment]
But the `view.file_name()` gives you back the file path of the file that is being edited that maybe outside the root of the project or in a deeper inner directory for example.

The `project_data` can exists even if there is no project file.

**Comment by LukasKalbertodt** [comment]
> The `project_data` can exists even if there is no project file.

How is this possible? 0_o But ok...

> But the `view.file_name()` gives you back the file path of the file that is being edited that maybe outside the root of the project or in a deeper inner directory for example.

Yes, but is that a problem? I don't think so, right? It's probably hardly the case that someone wants to format a file with settings that do not lie in any parent directory of the file. And if that's the case, the user can still manually set the path to the `rustfmt.toml` within the AnacondaRust settings.

So my point is: just using the path of the file is correct in at least 99% of all cases and thus a reasonable default.

**Comment by DamnWidget** [comment]
ST3 sets the `project_data`always that you open a folder even if there is no explicit project file, don't ask me why.

**Comment by DamnWidget** [comment]
v0.2.3 behaves as discussed

**Comment by LukasKalbertodt** [comment]
I think you [tagged](https://github.com/DamnWidget/anaconda_rust/releases/tag/v0.2.3) the wrong commit...

Sorry for all the inconvenience!

**Comment by DamnWidget** [comment]
Fixed

**Comment by LukasKalbertodt** [comment]
Seems to work now. Thanks a bunch!

**Pull request merged**
